# name: assembleDebug

# on:
#   push:
#     branches: [ develop ]
#   pull_request:
#     branches: [ develop ]

# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v1

#       - name: set up JDK 17
#         uses: actions/setup-java@v1
#         with:
#           java-version: 17

#       - name: Clean
#         run: |
#           ./scripts/cleanup.sh

#       - name: Build APK
#         run:  chmod +x .github/scripts/gradlew_recursive.sh ; .github/scripts/gradlew_recursive.sh assembleDebug
          
#       - name: Zip artifacts
#         run: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v1
#         with:
#           name: assembleDebug
#           path: assembleDebug.zip

